# Generated by Django 6.0.1 on 2026-02-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='custom_id',
            field=models.CharField(editable=False, max_length=8, null=True, unique=True),
        ),
    ]
