# Generated by Django 6.0.1 on 2026-02-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_role_user_custom_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STUDENT', 'Student'), ('ALUMNI', 'Alumni')], max_length=10, null=True),
        ),
    ]
