# Generated by Django 6.0.1 on 2026-02-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='query_id',
            field=models.CharField(blank=True, editable=False, max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
